application/models/__init__.py
# -*- coding: utf-8 -*-

from model import Book, User

__all__ = ['Book', 'User']

application/models/model.py
# -*- coding: utf-8 -*-

from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from application.extensions import db, login_manager

__all__ = ['Book', 'User']


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(64), unique=True, index=True)

    @property
    def password(self):
        raise AttributeError('')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Book(db.Model):
    """data model"""
    __tablename__ = 'book'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    posted_on = db.Column(db.Date, default=datetime.utcnow)

    def __init__(self, *args, **kwargs):
        super(Book, self).__init__(*args, **kwargs)

    def __repr__(self):
        return "<Book '%s'>" % self.title

    def store_to_db(self):
        """save to database"""

        db.session.add(self)
        db.session.commit()

    def delete_book(self):
        """delete data"""

        db.session.delete(self)
        db.session.commit()

application/__init__.py
# -*- coding: utf-8 -*-

from app import create_app
from app import db

__all__ = ['create_app', 'db']

application/app.py
# -*- coding: utf-8 -*-

from flask import Flask, render_template
from controllers import blueprints
from configs import config
from extensions import db, login_manager


def create_app(config_name=None):
    if config_name is None:
        config_name = 'default'

    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # db
    db.init_app(app)

    # login
    login_manager.init_app(app)

    # blueprints
    for bp in blueprints:
        app.register_blueprint(bp)

    handle_errors(app)

    return app


def handle_errors(app):
    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(403)
    def acess_forbidden_error(error):
        return render_template('403.html'), 403

application/controllers/__init__.py
# -*- coding: utf-8 -*-

import book
import movie
import user

blueprints = [
    book.book_bp,
    movie.movie_bp,
    user.user_bp
]

application/controllers/book.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, abort, redirect, url_for
from flask_login import login_required, current_user
from application.models import Book
from application.extensions import db

book_bp = Blueprint(
    'book',
    __name__,
    template_folder='../templates',
)


@book_bp.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@book_bp.route('/book', methods=['GET', 'POST'])
def show_book():
    books = Book.query.all()

    if request.method == 'POST':
        if not current_user.is_authenticated:
            abort(403)

        title = request.form["title"]
        book = Book(title=title)
        db.session.add(book)
        db.session.commit()
        return redirect(url_for('.show_book'))

    return render_template(
        'book.html',
        books=books
    )

application/controllers/movie.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, abort, redirect, url_for
from flask_login import current_user

movie_bp = Blueprint(
    'movie', 
    __name__,
    template_folder='../templates',
)

movies = ['The Name of the Rose', 'The Historian', 'Rebecca']


@movie_bp.route('/movie', methods=['GET', 'POST'])
def index():
    _form = request.form

    if request.method == 'POST':
        if not current_user.is_authenticated:
            abort(403)
        title = _form["title"]
        movies.append(title)
        return redirect(url_for('.index'))

    return render_template(
        'movie.html',
        movies=movies
    )


@movie_bp.route('/movie/<name>')
def info(name):
    movie = [name]
    if name not in movies:
        movie = []

    return render_template(
        'movie.html',
        movies=movie
    )

application/controllers/user.py
# -*- coding: utf-8 -*-

import re
from datetime import datetime

from flask import Blueprint, render_template
from flask import redirect, request, url_for
from flask_login import login_user, logout_user, login_required, current_user

from application.models import User
from application.extensions import db


user_bp = Blueprint(
    'user',
    __name__,
    template_folder='../templates'
)

alphanumeric = re.compile(r'^[0-9a-zA-Z_]*$')
email_address = re.compile(r'[a-zA-z0-9\.]+@[a-zA-Z0-9]+\.+[a-zA-Z]')


@user_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template(
            'signup.html',
            title=u'注册',
            form=None
        )
    elif request.method == 'POST':
        _form = request.form
        username = _form['username']
        email = _form['email']
        password = _form['password']
        password2 = _form['password2']

        message_e, message_u, message_p = "", "", ""

        # Check username is valid or not.
        if not username:
            message_u = u'用户名不能为空'
        elif not alphanumeric.match(username):
            message_u = u'用户名必须为字母、数字和下划线'
        elif User.query.filter_by(username=username).first():
            message_u = u'用户名已经存在'

        # Check email is valid or not.
        if not email:
            message_e = u'邮箱不能为空'
        elif not email_address.match(email):
            message_e = u'邮箱无效'
        elif User.query.filter_by(email=email).first():
            message_e = u'邮箱已经存在'

        # Check the password is valid or not.
        if password != password2:
            message_p = u'密码不对'
        elif password == "" or password2 == "":
            message_p = u'密码不能为空'

        if message_u or message_p or message_e:
            return render_template(
                "signup.html",
                form=_form,
                title=u'注册',
                message_u=message_u,
                message_p=message_p,
                message_e=message_e
            )

        # A valid register info, save the info into db.
        else:
            reg_user = User(username=username, email=email, password=password)
            db.session.add(reg_user)
            db.session.commit()
            login_user(reg_user)

            return redirect(url_for('user.signin'))


@user_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(request.args.get('next') or url_for("book.index"))
        return render_template(
            'signin.html',
            title=u'登录',
            form=None
        )
    elif request.method == 'POST':
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()
        if u and u.verify_password(_form['password']):
            login_user(u)
            u.last_login = datetime.now()
            db.session.commit()
            return redirect(request.args.get('next') or url_for('book.index'))
        else:
            message = u'无效的用户名或密码'

            return render_template(
                'signin.html',
                title=u'用户登录',
                form=_form,
                message=message
            )


@user_bp.route('/signout')
@login_required
def signout():
    logout_user()
    return redirect(url_for('book.index'))

application/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=360, initial-scale=0.75 user-scalable=no">
        {% block header_ext %}
        {% endblock %}
        <title>
            {% block title %}{% if title %}{{ title }}{% endif %}DEMO{% endblock %}
        </title>

        <!-- Bootstrap -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('book.index') }}">首页</a>
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('book.show_book') }}">读书</a></li>
                        <li><a href="{{ url_for('movie.index') }}">电影</a></li>
                    </ul>

                    {% if current_user.is_authenticated %}
                    <div class="navbar-form navbar-right">
                        <a class="btn btn-info" id="new-btn" href="{{ url_for('user.signout') }}">退出</a>
                    </div>
                    {% else %}
                    <div class="navbar-form navbar-right">
                        <ul class="nav navbar-nav">
                        <li class="dropdown">
                          <button type="button" class="btn btn-info btn-primary dropdown-toggle" data-toggle="dropdown">
                            登录  <b class="caret"></b>
                          </button>
                            <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.signin') }}">登录</a></li>
                            <li><a href="{{ url_for('user.signup') }}">注册?</a></li>
                            </ul>
                        </li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div><!--end nav container-->
        </nav><!--end nav-->

        <div id="wrap">
            <div class="container" id="main">
                <div class="row">
                    {% block inside_row %}
                    {% endblock %}
                </div><!--end outter row-->
            </div><!--end main-->
        </div><!--end wrap-->

        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {% block footer_ext %}{% endblock %}
    </body>
</html>

application/templates/book.html
{% extends 'base.html' %}

{% block inside_row %}
    {% if books %}
        <p>目前现有的书籍</p>
        {% for book in books %}
            <ul>
                <li> {{ book.title }} </li>
            </ul>
        {% endfor %}
    {% else %}
        <p> 暂时没有书籍,请先添加书籍</p>
    {% endif %}

    {% if current_user.is_authenticated %}
		<form class="form" action="{{ url_for('book.show_book') }}" method="post">
			<input id="title" name="title" placeholder="add book" type="text">
            <button type="submit">Submit</button>
		</form>
    {% else %}
		<div class="alert alert-info">添加书籍前请先登录</div>
		<a href="{{ url_for('user.signin', next=request.url) }}" class="btn btn-info">登录</a>
    {% endif %}
{% endblock %}

application/templates/index.html
{% extends 'base.html' %}
{% block inside_row %}
<div>
    {% if current_user.is_authenticated %}
        <h3>你好, {{ current_user.username }}</h3>
    {% else %}
        <h3>欢迎光临小站!</h3>
    {% endif %}

    <p>本站目前有两个频道:</p>
    <ul>
        <li><a href="{{ url_for('book.show_book') }}">读书</a></li>
        <li><a href="{{ url_for('movie.index') }}">电影</a></li>
    </ul>
</div>
{% endblock %}

application/templates/movie.html
{% extends 'base.html' %}

{% block inside_row %}
    {% if movies %}
        {% for movie in movies %}
            <ul>
                <li> {{ movie }} </li>
            </ul>
        {% endfor %}
    {% else %}
        <p> The movie doesn't exists! </p>
    {% endif %}


    <form method="post" action="{{ url_for('movie.index') }}">
        <input id="title" name="title" placeholder="add movie" type="text">
        <button type="submit">Submit</button>
    </form>
{% endblock %}

application/templates/signin.html
{% extends 'base.html' %}
{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3">

    <form class="panel-body" role="form" method="post" action="{{ url_for('user.signin', next=request.args.get('next')) }}">
        <h2 class="text-center" style="margin-bottom:1em"> 用户登录 </h2>
        {% if message %}
		<div class="messages"> <p class="text-danger"> {{ message }} </p></div>
		{% endif %}
        <div class="form-group ">
            <label for="email"> 邮箱 </label>
            <input class="form-control" id="email" name="email" placeholder=example@gmail.com type="text" value="{{ form.email }}">
        </div>

        <div class="form-group ">
            <label for="password"> 密码 </label>
            <input class="form-control" id="password" name="password" type="password" value="{{ form.password }}">
        </div>

        <div class="form-group">
            <button class="btn btn-default btn-success pull-right">
                登录
            </button>
            <a class="btn btn-link pull-right" href="{{ url_for('user.signup') }}">注册</a>
        </div>
    </form>
</div>
{% endblock %}

application/templates/signup.html
{% extends 'base.html' %}
{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3">
    <form class="panel-body" role="form" method="post" action="{{ url_for('user.signup') }}">
        <h2 class="text-center" style="margin-bottom:1em">注册一个帐号</h2>
    
        <div class="form-group ">
            <label for="username">用户名</label>
            <input class="form-control" id="username" name="username" placeholder="字母数字和下划线" type="text" value="{{ form.username }}">
            {% if message_u %} <div class="messages"> <p class="text-danger"> {{ message_u }} </p> </div> {% endif %}
        </div>

        <div class="form-group ">
            <label for="email">邮箱</label>
            <input class="form-control" id="email" name="email" type="email" placeholder="" value="{{ form.email }}" >
            {% if message_e %} <div class="messages"> <p class="text-danger"> {{ message_e }} </p> </div> {% endif %}
        </div>

        <div class="form-group ">
            <label for="password">密码</label>
            <input class="form-control" id="password" name="password" type="password" value="{{ form.password }}">
        </div>

         <div class="form-group ">
            <label for="password">再次输入密码</label>
            <input class="form-control" id="password2" name="password2" type="password" value="{{ form.password2 }}">
             {% if message_p %} <div class="messages"> <p class="text-danger"> {{ message_p }} </p> </div> {% endif %}
        </div>

        <div class="form-group">
            <button class="btn btn-success pull-right">注册</button>
            <a class="btn btn-link pull-right" href="{{ url_for('user.signin') }}">登录</a>
        </div>
    </form>
</div>
{% endblock %}